### ISSUE TITLE
Improvement: Extend --set-pvalue Functionality for Cookies, Headers, Queries and ETC

### ISSUE THREAD

**Issue by hahwul** [owasp-noir/noir#395]
> From this discussion https://github.com/owasp-noir/noir/pull/394#issue-2526429180

@ksg97031 
How about handling `--set-pvalue` like this?

--set-pvalue: Set values for all parameters
--set-pvalue-cookie: Set values specifically for cookie parameters
--set-pvalue-header: Set values specifically for header parameters
--set-pvalue-query: Set values specifically for query parameters
etc...

It's just an idea, but is there a better way to do this?

**Comment by ksg97031** [comment]
Yes, I also think separating the options by parameter types is a good approach.
Additionally, how about supporting a key/value pair format for `set-pvalue*` parameters?

For example:

`--set-pvalue page=1 --set-pvalue test`
Structure: `/<page>?param={param}`
Result: `/1?param=test`

`--set-pvalue year=2024 --set-pvalue month=09`
Structure: `/<year>/<month>/calendar.html`
Result: `/2024/09/calendar.html`

`--set-pvalue-path id=395 --set-pvalue-query id=ksg97031`
Structure: `/posts/<id>?id={id}`
Result: `/posts/395?id=ksg97031`

Would it be feasible to implement it this way?

**Comment by hahwul** [comment]
@ksg97031 
Sure, that's a great idea!! So let's roll up our sleeves and get it done🔥
