### ISSUE TITLE
Consider adding a `--show-status` flag to display HTTP status codes for discovered endpoints when using the URL option

### ISSUE THREAD

**Issue by ksg97031** [owasp-noir/noir#397]
### Suggestion:
When using the URL option, introduce a `--show-status` flag that outputs the HTTP status codes of the discovered endpoints. This enhancement will help users quickly identify the status of endpoints and make decisions based on the response codes.

### Detailed Explanation:
- **Current Behavior**:  
  - When the URL option is used, the tool finds and lists endpoints, but does not display their HTTP status codes.  

- **Proposed Enhancement**:  
  - Introduce a new flag `--show-status` that, when enabled, will display the HTTP status code for each discovered endpoint.  
  - This will help users quickly see which endpoints are returning errors (e.g., 404, 500) or are functioning correctly (e.g., 200).  

- **Future Extension**:  
  - In future iterations, consider adding options like `--exclude-status` to exclude endpoints with specific status codes when delivering results.
  - This would provide more flexibility and improve the efficiency of the deliver functionality by filtering out unnecessary endpoints.  

#### Benefits:  
- Saves time by directly displaying the status of endpoints.  
- Helps users focus on valid and functional endpoints.  
- Provides a foundation for future enhancements, such as filtering by specific status codes.

**Comment by hahwul** [comment]
@ksg97031 
Great idea! It's not a difficult task, so let's get started quickly.
